# Generated by Django 4.0.1 on 2022-05-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_active_order',
            field=models.BooleanField(blank=True),
        ),
    ]
