# Generated by Django 4.0.1 on 2022-05-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_order_is_active_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_active_order',
            field=models.BooleanField(),
        ),
    ]
