# Generated by Django 4.0.1 on 2022-05-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_order_is_active_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
