# Generated by Django 4.0.1 on 2022-05-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='is_main_car',
            field=models.BooleanField(default=False, verbose_name='Головна машина?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_active_order',
            field=models.BooleanField(verbose_name='Ремонт закінчений'),
        ),
    ]
