# Generated by Django 4.0.1 on 2022-05-24 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_cars_is_main_car_alter_order_is_active_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='marka',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='model',
        ),
    ]
