# Generated by Django 4.0.1 on 2022-05-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_marka_remove_profile_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_active_order',
        ),
        migrations.AddField(
            model_name='order',
            name='is_completed_repair',
            field=models.BooleanField(default=False, verbose_name='Ремонт закінчений'),
        ),
    ]
