# Generated by Django 4.0.1 on 2022-05-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_order_year_of_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(default='Наразі не встановлена', max_length=10, verbose_name='Вартість послуги'),
        ),
    ]
