# Generated by Django 4.0.1 on 2022-06-06 16:28

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ім`я, прізвище')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Email користувача')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефону')),
                ('address_order', models.CharField(max_length=200, verbose_name='Адреса доставки')),
                ('comment', models.TextField(default='---------', verbose_name='Коментар до замовлення')),
                ('composition_order', models.TextField(verbose_name='Замовлення')),
                ('summa', models.CharField(max_length=15, verbose_name='Сума (грн)')),
                ('status', models.CharField(choices=[('Замовлення в процесі', 'Замовлення в процесі'), ('Користувач забрав товар', 'Користувач забрав товар'), ('Користувач не розрахувався', 'Користувач не розрахувався')], default='Замовлення в процесі', max_length=200, verbose_name='Статус')),
                ('date_field', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата замовлення')),
            ],
        ),
        migrations.AddField(
            model_name='typeofrepair',
            name='icon',
            field=models.ImageField(default='shop/static/shop/shinomontazh.png', upload_to='user_images', verbose_name='Іконка'),
        ),
    ]
