# Generated by Django 4.0.1 on 2022-06-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_partsorder_summa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsorder',
            name='summa',
            field=models.CharField(default='', max_length=15, verbose_name='Сума (грн)'),
        ),
    ]
