# Generated by Django 4.0.1 on 2022-06-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_partsorder_summa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsorder',
            name='address_order',
        ),
        migrations.AddField(
            model_name='partsorder',
            name='address_city',
            field=models.CharField(default='САМОВИВІЗ', max_length=200, verbose_name='Адреса міста доставки'),
        ),
        migrations.AddField(
            model_name='partsorder',
            name='address_vidd',
            field=models.CharField(default='САМОВИВІЗ', max_length=200, verbose_name='Адреса відділення доставки'),
        ),
    ]
