# Generated by Django 4.0.1 on 2022-06-10 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_partsorder_address_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partsorder',
            options={'verbose_name': 'Замовлення запчастин', 'verbose_name_plural': 'Замовлення запчастин'},
        ),
    ]
