# Generated by Django 4.0.1 on 2022-06-10 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_partsorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення ремонту', 'verbose_name_plural': 'Замовлення ремонту'},
        ),
    ]
