# Generated by Django 4.0.1 on 2022-06-10 02:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_order_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UndefinedParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.IntegerField(verbose_name='ID замовлення')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я замовника")),
                ('product', models.CharField(max_length=50, verbose_name='Назва продукту')),
                ('count_product', models.IntegerField(verbose_name='Кількість замовленого продукту')),
                ('date_field', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата замовлення')),
            ],
            options={
                'verbose_name': 'Не визначені запчастини',
                'verbose_name_plural': 'Не визначені запчастини',
            },
        ),
    ]
