# Generated by Django 4.0.1 on 2022-06-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_undefinedparts'),
    ]

    operations = [
        migrations.AddField(
            model_name='undefinedparts',
            name='id_of_product',
            field=models.IntegerField(default=1, verbose_name='ID продукту'),
        ),
    ]
