# Generated by Django 4.0.1 on 2022-06-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_profile_is_new_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsorder',
            name='is_authenticated_user',
            field=models.CharField(default='Не зареєстрований', max_length=20, verbose_name='id користувача або не зареєстрований'),
        ),
    ]
