# Generated by Django 4.0.1 on 2022-06-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_partsorder_is_authenticated_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='abracadabra@ukr.net', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='partsorder',
            name='is_authenticated_user',
            field=models.CharField(default='Не зареєстрований', max_length=20, verbose_name='id користувача або не зареєстрований(0). ПОЛЕ НЕ РЕДАГУВАТИ!!!'),
        ),
    ]
