# Generated by Django 4.0.1 on 2022-06-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_profile_email_alter_partsorder_is_authenticated_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsorder',
            name='is_authenticated_user',
            field=models.CharField(default='Не зареєстрований', max_length=20, verbose_name='id користувача або не зареєстрований(0)'),
        ),
    ]
