# Generated by Django 4.0.1 on 2022-06-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_availablemarks_category_products_delete_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Кількість товару в наявності'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='static/shop/fon.jpg', upload_to='details_photo', verbose_name='Фото товару'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Назва'),
        ),
    ]
