# Generated by Django 4.0.1 on 2022-06-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_products_count_alter_products_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PidMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Марка для підшипників',
                'verbose_name_plural': 'Марки для підшипників',
                'ordering': ['name'],
            },
        ),
    ]
