# Generated by Django 4.0.1 on 2022-04-01 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='static/shop/fon.jpg', upload_to='details_photo'),
        ),
    ]
