# Generated by Django 4.0.1 on 2022-04-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_products_date_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(default='Vitya', max_length=200, unique=True),
        ),
    ]
