# Generated by Django 4.0.1 on 2022-04-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Available Mark',
                'verbose_name_plural': 'Available Marks',
            },
        ),
    ]
