# Generated by Django 4.0.1 on 2022-04-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_availablemarks_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availablemarks',
            options={'ordering': ['name'], 'verbose_name': 'Available Mark', 'verbose_name_plural': 'Available Marks'},
        ),
    ]
